### ISSUE TITLE
import issue

### ISSUE THREAD

**Issue by nerddan** [EliorBenYosef/reinforcement-learning#4]
How am I supposed to run this project?

When I try to run any `.py` file, I got 

```
ModuleNotFoundError: No module named 'reinforcement_learning'
```

or

```
ModuleNotFoundError: No module named 'tests'
```

**Comment by EliorBenYosef** [comment]
I need some specifics...
do you run it from the IDE or from the terminal?

**Comment by nerddan** [comment]
I am running it from the terminal

```
> python reinforcement_learning/deep_RL/utils/cmdline_play.py
Traceback (most recent call last):
  File "~/reinforcement-learning/reinforcement_learning/deep_RL/utils/cmdline_play.py", line 5, in <module>
    from tests.test_deep_rl.test_dql import play_dql
ModuleNotFoundError: No module named 'tests'
```

**Comment by EliorBenYosef** [comment]
yeah, I patched that up earlier today.
make sure you have the latest version of cmdline_play, and type in the root terminal:
`python -m reinforcement_learning.deep_RL.utils.cmdline_play`
(this is also mentioned in the updated cmdline_play)

tell me if that solved it for you.

**Comment by nerddan** [comment]
It worked!

Can I use tf2 with this repo?

**Comment by EliorBenYosef** [comment]
happy to hear :)

right now the TF part is TF and not TF2... :/
I'm planning on updating it to TF2, but I'm not sure when I'll get to it

**Comment by nerddan** [comment]
Looks like the argument list does not match.

https://github.com/EliorBenYosef/reinforcement-learning/blob/master/tests/test_deep_rl/test_ac.py#L18

https://github.com/EliorBenYosef/reinforcement-learning/blob/master/reinforcement_learning/deep_RL/utils/cmdline_play.py#L160

**Comment by EliorBenYosef** [comment]
you're right. it's fixed now.
